### ISSUE TITLE
Got an error SDK when I wanted to claim my pending reward

### ISSUE THREAD

**Issue by cckole** [samvanemelen/debato#9]
### Description
I got an SDK error when I wanted to claim my reward.

### Expected behaviour

I expected that my reward will be claimed when I initiated the process by clicking on claim reward

### Steps to reproduce

- Type debato.org on a browser ( I used Chrome) and load it.

- Click the log in button and type in your steem user name and active key in the spaces provided.

- After login in, click on the menu by the top left side.

- Click on profile

- Click on wallet and scroll down to claim reward. Make sure you have a pending reward available.

- Click on claim reward and note the error.

### Reproducing the bug

https://youtu.be/uKD6V8PvWQc

### Device used

Tekno spark K7

### Version

Android 7.0

Browser used: Chrome

**Comment by samvanemelen** [comment]
Do you also get the error when claiming the reward via a desktop?

**Comment by cckole** [comment]
Yes. I got the same error on my PC as well. SDK error..

**Comment by samvanemelen** [comment]
Thank you! The error should have been fixed. The issue was that different login links existed that do not all ask for the same permission (such as claiming rewards). This has been fixed and all links should automatically be complete. It is probably necessary to log out, and log in again to make it work again. Can you confirm if it works again on your device? than I can close the issue

**Comment by cckole** [comment]
Yes, I just logged in and out and it worked fine. I was able to claim my rewards. Nice job..
